export const ORDER_EVENT_TYPES = {
  REGISTERED: 'REGISTERED',
  ASSIGNED: 'ASSIGNED',
  TRANSIT_STARTED: 'TRANSIT_STARTED',
  DELIVERED: 'DELIVERED',
  OBSERVED: 'OBSERVED',
  REASSIGNED: 'REASSIGNED',
  DRIVER_UNASSIGNED: 'DRIVER_UNASSIGNED',
  FORCE_CLOSED_BY_ADMIN: 'FORCE_CLOSED_BY_ADMIN',
  AUTO_CLOSED_EOD: 'AUTO_CLOSED_EOD',
  STOP_GROUPED: 'STOP_GROUPED',
  STOP_UNGROUPED: 'STOP_UNGROUPED',
  WHATSAPP_SENT: 'WHATSAPP_NOTIFICATION_SENT',
  WHATSAPP_FAILED: 'WHATSAPP_NOTIFICATION_FAILED',
  WHATSAPP_WAREHOUSE_SENT: 'WHATSAPP_WAREHOUSE_NOTIFICATION_SENT',
  WHATSAPP_WAREHOUSE_FAILED: 'WHATSAPP_WAREHOUSE_NOTIFICATION_FAILED',
} as const;

export type OrderEventType = (typeof ORDER_EVENT_TYPES)[keyof typeof ORDER_EVENT_TYPES];
